package csg;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CSGManagerProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // NEW TEXT
    //TADATA TAB
    UNDERGRAD_COLUMN_TEXT,
    
    //COURSE DETAILS TAB
    //COURSE DETAILS PANE
    COURSE_INFO_LABEL_TEXT,
    SUBJECT_LABEL_TEXT,
    NUMBER_LABEL_TEXT,
    SEMESTER_LABEL_TEXT,
    YEAR_LABEL_TEXT,
    TITLE_LABEL_TEXT,
    INSTRUCTOR_NAME_LABEL_TEXT,
    INSTRUCTOR_HOME_LABEL_TEXT,
    EXPORT_DIR_LABEL_TEXT,
    EXPORT_DIR_PATH_LABEL_TEXT,
    CHANGE_DIR_BUTTON_TEXT,
    // SITE TEMPLATE PANE
    SITE_TEMPLATE_LABEL_TEXT,
    SITE_TEMPLATE_INFO_LABEL_TEXT,
    TEMPLATE_DIR_LABEL_TEXT,
    SELECT_TEMPLATE_DIR_BUTTON_TEXT,
    SITE_PAGES_LABEL_TEXT,
    USE_COLUMN_TEXT,
    NAVBAR_TITLE_COLUMN_TEXT,
    FILE_NAME_COLUMN_TEXT,
    SCRIPT_COLUMN_TEXT,
    //  PAGE STYLE PANE
    PAGE_STYLE_LABEL_TEXT,
    BANNER_SCHOOL_IMG_LABEL_TEXT,
    IMG_CHANGE_BUTTON_TEXT,
    LEFT_FOOTER_IMG_LABEL_TEXT,
    RIGHT_FOOTER_IMG_LABEL_TEXT,
    STYLESHEET_LABEL_TEXT,
    NOTE_LABEL_TEXT,
    
    //RECITATION DATA TAB
    RECITATIONS_LABEL_TEXT,
    SECTION_COLUMN_TEXT,
    INSTRUCTOR_COLUMN_TEXT,
    DAY_TIME_COLUMN_TEXT,
    LOCATION_COLUMN_TEXT,
    ADD_EDIT_LABEL_TEXT,
    SECTION_LABEL_TEXT,
    INSTRUCTOR_LABEL_TEXT,
    DAY_TIME_LABEL_TEXT,
    LOCATION_LABEL_TEXT,
    SUPERVISING_TA_LABEL_TEXT,
    ADD_UPDATE_BUTTON_TEXT,
    
    
    
    //SCHEDULE DATA TAB
    SCHEDULE_LABEL_TEXT,
    CALENDAR_BOUNDARIES_LABEL_TEXT,
    STARTING_MONDAY_LABEL_TEXT,
    ENDING_FRIDAY_LABEL_TEXT,
    SCHEDULE_ITEMS_LABEL_TEXT,
    TYPE_COLUMN_TEXT,
    DATE_COLUMN_TEXT,
    TITLE_COLUMN_TEXT,
    TOPIC_COLUMN_TEXT,
    TYPE_LABEL_TEXT,
    DATE_LABEL_TEXT,
    TIME_LABEL_TEXT,
    LINK_LABEL_TEXT,
    TOPIC_LABEL_TEXT,
    
    CRITERIA_LABEL_TEXT,
    
    //PROJECT DATA TAB
    PROJECTS_LABEL_TEXT,
    TEAMS_HEADER_LABEL_TEXT,
    COLOR_COLUMN_TEXT,
    TEXT_COLOR_COLUMN_TEXT,
    LINK_COLUMN_TEXT,
    NAME_LABEL_TEXT,
    COLOR_LABEL_TEXT,
    TEXT_COLOR_LABEL_TEXT,
    STUDENT_LABEL_TEXT,
    FIRST_NAME_COLUMN_TEXT,
    LAST_NAME_COLUMN_TEXT,
    TEAM_COLUMN_TEXT,
    ROLE_COLUMN_TEXT,
    ADD_EDIT_LABEL2_TEXT,
    FIRST_NAME_LABEL_TEXT,
    LAST_NAME_LABEL_TEXT,
    TEAM_LABEL_TEXT,
    ROLE_LABEL_TEXT,
    
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    
    INVALID_TIME_TITLE,
    INVALID_TIME_MESSAGE,
    WARNING_TIME_TITLE,
    WARNING_TIME_MESSAGE,
    
    INVALID_TA_EMAIL_TITLE,
    INVALID_TA_EMAIL_MESSAGE
}
